-- Your SQL goes here
INSERT INTO apartments (name,
                        email,
                        phone,
                        address,
                        accepted_school_email_domain,
                        free_tier_hours, free_tier_rate,
                        silver_tier_hours, silver_tier_rate,
                        gold_tier_hours, gold_tier_rate,
                        platinum_tier_hours, platinum_tier_rate,
                        duration_rate,
                        liability_protection_rate,
                        pcdw_protection_rate,
                        pcdw_ext_protection_rate,
                        rsa_protection_rate,
                        pai_protection_rate,
                        sales_tax_rate,
                        is_operating,
                        is_public)
VALUES ('Veygo HQ',
        'admin@veygo.rent',
        '8334683946',
        '101 Foundry Dr, Ste 1200, West Lafayette, IN 47906',
        'veygo.rent',
        0.0, 0.0,
        0.0, 0.0,
        0.0, 0.0,
        0.0, 0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        TRUE,
        TRUE);