ALTER TABLE charges
DROP
COLUMN IF EXISTS taxes;

ALTER TABLE agreements
DROP
COLUMN IF EXISTS taxes,
    ADD COLUMN tax_rate FLOAT8 NOT NULL DEFAULT 0.0;

ALTER TABLE apartments
DROP
COLUMN IF EXISTS taxes,
    ADD COLUMN sales_tax_rate FLOAT8 NOT NULL DEFAULT 0.0;

DROP TABLE IF EXISTS taxes;
