-- Your SQL goes here
INSERT INTO apartments (name,
                        email,
                        phone,
                        address,
                        accepted_school_email_domain,
                        free_tier_hours, free_tier_rate,
                        silver_tier_hours, silver_tier_rate,
                        gold_tier_hours, gold_tier_rate,
                        platinum_tier_hours, platinum_tier_rate,
                        duration_rate,
                        liability_protection_rate,
                        pcdw_protection_rate,
                        pcdw_ext_protection_rate,
                        rsa_protection_rate,
                        pai_protection_rate,
                        sales_tax_rate,
                        is_operating,
                        is_public,
                        is_uni)
VALUES ('Purdue University',
        'newres@purdue.edu',
        '7654944600',
        '610 Purdue Mall, West Lafayette, IN 47907',
        'purdue.edu',
        0.5, 0.0,
        2.0, 71.99,
        5.0, 192.88,
        10.0, 305.49,
        12.5,
        0.0,
        2.1,
        0.0,
        0.0,
        0.0,
        11.0,
        TRUE,
        TRUE,
        TRUE)
    ON CONFLICT (name) DO NOTHING;